name: rapids
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - arxiv=1.4.7
  - redis=3.5.3
  - click=8.1.7
  - pandas=2.0.3
  - tqdm=4.65.0
  - beautifulsoup4=4.12.3
  - requests=2.32.3
  - openai=1.59.0
  - pydantic=2.10.4
  - rich=13.9.4
  - colorama=0.4.6
  - jsonschema=4.20.0
  - pip
  - pip:
    - black==23.12.1
    - pytest==7.4.4
    - pytest-cov==4.1.0
    - python-dotenv==1.0.0
    - typer==0.9.0
    - loguru==0.7.2
    - tenacity==8.2.3
    - openrouter-py==0.3.2
