name: rapids
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - arxiv=1.4.7
  - redis=3.5.3
  - click=8.1.7
  - pandas=2.0.3
  - tqdm=4.65.0
  - beautifulsoup4=4.12.3
  - requests=2.32.3
  - pip
  - pip:
    - black
    - pytest
    - pytest-cov
